language: python
python:
  - "3.4"
#  - "3.5.0b3"
#  - "nightly"
# command to install dependencies
addons:
  apt:
    packages:
    - qt4-qmake
    - libqt4-dev
    - python3-pyside
install: "pip install -r requirements_travis.txt"
# command to run tests
script: nosetests