language: python
python:
  - "3.4"
#  - "3.5.0b3"
#  - "nightly"
# command to install dependencies
addons:
  apt:
    packages:
    - qt4-qmake
    - libqt4-dev
install:
  - pip install pycrypto
  - pip install requests
  - pip install PySide
# command to run tests
script: nosetests