language: python
python:
  - "3.4"
#  - "3.5.0b3"
#  - "nightly"
# command to install dependencies
addons:
  apt:
    packages:
    - qt4-qmake
    - libqt4-dev
install:
  - pip install pycrypto
  - pip install requests
  - pip install PySide --no-index --find-links http://parkin.github.io/python-wheelhouse/PySide-1.2.2-cp34-cp34m-linux_x86_64.whl
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
# command to run tests
script: nosetests